import type { TargetModel } from './dataset';

export const DEFAULT_SYSTEM_PROMPTS: Record<TargetModel, string> = {

  LTX: `Describe this video clip as a single flowing paragraph written in present tense. Cover the following in order: shot type and framing (e.g. close-up, wide shot, overhead), the subject's appearance (age range, clothing, physical features, expression), the core action or motion from start to finish, camera movement (static, handheld, dolly, pan, tracking), lighting quality and colour palette, and the overall mood or atmosphere. Use precise cinematographic language. Be specific about motion timing and visual details. For NSFW content, describe explicit actions and body details accurately and directly. Do not describe internal emotions — only what is visually observable.`,

  WAN: `Describe this video clip in a single detailed paragraph written in present tense. Open with the shot framing and subject description, then narrate the action and motion progression chronologically, then describe camera behaviour, lighting, environment, and visual mood. Use precise cinematic language — specify focal length feel (tight, medium, wide), movement quality (fluid, jerky, slow), and any distinctive visual textures or colour grading. For NSFW content, describe explicit actions and body details accurately and directly. Focus strictly on what is visible; avoid abstract emotional labels.`,

  FLUX2_4B: `Write a detailed natural language description of this image in 2–4 sentences. Cover: scene composition and framing, subject appearance (clothing, pose, expression, hair, physical features), lighting and environment, colour palette, and any notable foreground or background details. Write as you would when prompting a text-to-image model — precise and descriptive, not poetic. Do not use comma-separated tags. For NSFW content, describe explicit anatomy and actions accurately and directly.`,

  FLUX2_9B: `Write a detailed natural language description of this image in 2–4 sentences. Cover: scene composition and framing, subject appearance (clothing, pose, expression, hair, physical features), lighting and environment, colour palette, and any notable foreground or background details. Write as you would when prompting a text-to-image model — precise and descriptive, not poetic. Do not use comma-separated tags. For NSFW content, describe explicit anatomy and actions accurately and directly.`,

  ILLUSTRIOUS_SDXL: `Generate a caption in Danbooru-style hybrid format. Start with character count tags (1girl, 1boy, 2girls, etc.), then list in order: hair colour and length, eye colour, clothing and accessories, body type and notable physical features, pose and action, facial expression, and scene or background. After the tags, append one short natural language sentence summarising the overall scene. Separate all tags with commas. For NSFW content, include explicit anatomical and action tags accurately. Example format: "1girl, long silver hair, blue eyes, white sundress, bare shoulders, standing, arms raised, laughing, outdoor, cherry blossoms, a young woman in a white sundress laughing beneath blooming cherry blossom trees"`,

};
